#		Make WorldWideWeb daemons
#
# 	First, set environment variable WWW_MACH to your
#	machine architecure type.
#
include ../../Library/$(WWW_MACH)/Makefile.include
include ../Implementation/CommonMakefile
